FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build 
WORKDIR /src

COPY *.sln .
COPY PolicyService/Insurance.Policy.Api/*.csproj PolicyService/Insurance.Policy.Api/
COPY PolicyService/Insurance.Policy.Application/*.csproj PolicyService/Insurance.Policy.Application/
COPY PolicyService/Insurance.Policy.Domain/*.csproj PolicyService/Insurance.Policy.Domain/
COPY PolicyService/Insurance.Policy.Infrastructure/*.csproj PolicyService/Insurance.Policy.Infrastructure/

RUN dotnet restore Insurance.QuoteAndPolicy.sln

COPY . .

WORKDIR /src/PolicyService/Insurance.Policy.Api
RUN dotnet publish -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app
COPY --from=build /app/publish .

ENV ASPNETCORE_URLS=http://+:8080 
EXPOSE 8080 

ENTRYPOINT ["dotnet", "Insurance.Policy.Api.dll"]