FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build 
WORKDIR /src

COPY *.sln .
COPY QuoteService/Insurance.Quote.Api/*.csproj QuoteService/Insurance.Quote.Api/
COPY QuoteService/Insurance.Quote.Application/*.csproj QuoteService/Insurance.Quote.Application/
COPY QuoteService/Insurance.Quote.Domain/*.csproj QuoteService/Insurance.Quote.Domain/
COPY QuoteService/Insurance.Quote.Infrastructure/*.csproj QuoteService/Insurance.Quote.Infrastructure/

RUN dotnet restore Insurance.QuoteAndQuote.sln

COPY . .

WORKDIR /src/QuoteService/Insurance.Quote.Api
RUN dotnet publish -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app
COPY --from=build /app/publish .

ENV ASPNETCORE_URLS=http://+:8080 
EXPOSE 8080 

ENTRYPOINT ["dotnet", "Insurance.Quote.Api.dll"]