// <auto-generated />
using System;
using Insurance.Quote.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Insurance.Quote.Infrastructure.Migrations
{
    [DbContext(typeof(QuoteContext))]
    partial class QuoteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Quote.Domain.Entities.CustomerEntity", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("BirthDate")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("text");

                    b.HasKey("CustomerId");

                    b.HasIndex("DocumentNumber");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("Quote.Domain.Entities.ProductEntity", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("ProductId");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("Quote.Domain.Entities.QuoteEntity", b =>
                {
                    b.Property<Guid>("QuoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("quote_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CustomerEntityCustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("EstimatedValue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("InsuranceType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("ProductEntityProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("QuoteId");

                    b.HasIndex("CustomerEntityCustomerId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductEntityProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("Quotes", (string)null);
                });

            modelBuilder.Entity("Quote.Domain.Entities.QuoteEntity", b =>
                {
                    b.HasOne("Quote.Domain.Entities.CustomerEntity", null)
                        .WithMany("Quotes")
                        .HasForeignKey("CustomerEntityCustomerId");

                    b.HasOne("Quote.Domain.Entities.CustomerEntity", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quote.Domain.Entities.ProductEntity", null)
                        .WithMany("Quotes")
                        .HasForeignKey("ProductEntityProductId");

                    b.HasOne("Quote.Domain.Entities.ProductEntity", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Quote.Domain.Entities.CustomerEntity", b =>
                {
                    b.Navigation("Quotes");
                });

            modelBuilder.Entity("Quote.Domain.Entities.ProductEntity", b =>
                {
                    b.Navigation("Quotes");
                });
#pragma warning restore 612, 618
        }
    }
}
